name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git commit hash
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2 }} << 'ENDSSH'
          curl -X POST "https://discord.com/api/v9/channels/1257316921565646878/messages" -H "Authorization: Bot ${{ secrets.DISCORD_TOKEN }}" -H "Content-Type: application/json" -d '{"content": "\`\`\`Shutting down bot for update...\`\`\`"}'
          cd /home/ubuntu/SchoolBot
          sudo git pull
          sudo docker container stop bot
          sudo docker container rm bot
          sudo docker image rm estonian/discord-bot:latest
          sudo docker build -t estonian/discord-bot:latest .
          sudo docker run -e DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}} -e LOGIN=${{secrets.LOGIN}} -e PASSWORD=${{secrets.PASSWORD}} -e GIT_COMMIT=${{ env.GIT_COMMIT }} -d --name bot estonian/discord-bot:latest 
          ENDSSH
